### ISSUE TITLE
Error al "Crear Plantillas" para colecciones

### ISSUE THREAD

**Issue by KharolusIII** [uner-digital/DSpace#76]
Intenté crear una plantilla y cuando agrego un metadato me da el siguiente mensaje de error: 

`The metadata field "dc_type" requires an authority key but none was provided. Value="Articulo"`

Esto se debe a que cuando se agrega un **metadato controlado por autoridad** (en este caso *dc.type*) a la planilla de una collection, el formulario no detecta que es un metadato controlado por autoridad.

> Java stacktrace: java.lang.IllegalArgumentException: The metadata field "dc_type" requires an authority key but none was provided. Value="Articulo"
	at org.dspace.content.DSpaceObjectServiceImpl.addMetadata(DSpaceObjectServiceImpl.java:262)
	at org.dspace.content.DSpaceObjectServiceImpl.addMetadata(DSpaceObjectServiceImpl.java:321)
	at org.dspace.content.DSpaceObjectServiceImpl.addMetadata(DSpaceObjectServiceImpl.java:213)
	at org.dspace.content.DSpaceObjectServiceImpl.addMetadata(DSpaceObjectServiceImpl.java:299)
	at org.dspace.app.xmlui.aspect.administrative.FlowItemUtils.processAddMetadata(FlowItemUtils.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:155)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:243)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3237)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2394)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:2834)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:160)
	at org.mozilla.javascript.Context.call(Context.java:538)
	at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:1833)
	at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:1803)
	at org.apache.cocoon.components.flow.javascript.fom.FOM_JavaScriptInterpreter.handleContinuation(FOM_JavaScriptInterpreter.java:698)
	at org.apache.cocoon.components.treeprocessor.sitemap.CallFunctionNode.invoke(CallFunctionNode.java:94)
	...

[Full Stacktrace][1]

  [1]: http://pastebin.com/1D53ztEa

**Comment by FacundoAdorno** [comment]
Ahora se pueden agregar metadatos controlados por autoridad durante la vista de "Crear plantilla de colección", y además se pueden agregar metadatos controlados por autoridad a la vista de "Editar item". Esto ultimo fue repercusión del cambio ya que la creación de plantillas y la edición de un item ya archivado utilizan el mismo aspecto "EditItemMetadataForm".

La vista ahora tiene un botón de **Lookup** el cual se habilita o deshabilita según el metadato que en ese momento se está agregando. La selección de autoridad tiene que hacerse obligatoriamente desde este botón.

![editar_plantilla_coleccion](https://cloud.githubusercontent.com/assets/6214284/23038385/96535116-f468-11e6-8f4e-dc449d3bf795.png)
